# Generated by Django 5.0.3 on 2024-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='keywords',
            field=models.ManyToManyField(related_name='images', to='img_app.keyword'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='object_key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
