# Generated by Django 5.0.3 on 2024-03-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_alter_imagemodel_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='object_url',
            field=models.URLField(unique=True),
        ),
    ]
