# Generated by Django 5.0.3 on 2024-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0003_alter_imagemodel_object_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=100, unique=True)),
                ('region_name', models.CharField(blank=True, max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('bucket_name', 'region_name')},
            },
        ),
    ]
