# Generated by Django 5.0.3 on 2024-03-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0004_lookupbucket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lookupbucket',
            unique_together={('bucket_name', 'prefix')},
        ),
    ]
